services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: forum-with-ddd
      PGDATA: /.docker/data/postgres
    volumes:
      - ./.docker/data/pg:/data/postgres
